"""Team Copilot Tests - Integration Tests - Users - Create User."""

from uuid import uuid4
from datetime import datetime, timezone
from unittest.mock import patch

from fastapi import FastAPI, status
from fastapi.testclient import TestClient

from team_copilot.core.auth import get_admin_user
from team_copilot.models.data import User

from tests.integration import raise_not_authorized_exc


def test_create_user(app: FastAPI, test_client: TestClient, test_admin_user: User):
    """Test the "create_user" endpoint.

    Args:
        app (FastAPI): FastAPI application.
        test_client (TestClient): FastAPI test client.
        test_admin_user (User): Mock enabled administrator user.
    """
    # Simulate the injected dependency
    app.dependency_overrides[get_admin_user] = lambda: test_admin_user

    user_id = uuid4()
    now = datetime.now(timezone.utc)

    # Request data
    req_data = {
        "username": "newuser",
        "password": "newusernewuser",
        "name": "New User",
        "email": "newuser@example.com",
        "staff": False,
        "admin": False,
        "enabled": True,
    }

    with (
        patch("team_copilot.routers.users.get_us", return_value=None) as mock_get_user,
        patch("team_copilot.routers.users.save_user") as mock_save_user,
    ):
        # Configure the "save_user" mock to simulate the fields of the user that are
        # generated by the database server when creating a user ("id", "created_at"
        # and "updated_at").
        def side_effect(u: User):
            u.id = user_id
            u.created_at = now
            u.updated_at = now

        mock_save_user.side_effect = side_effect

        # Make HTTP request
        response = test_client.post("/users", json=req_data)

        # Check response
        assert response.status_code == status.HTTP_201_CREATED

        res_data = response.json()
        assert len(res_data) == 2

        assert (
            res_data["message"] == f'User {user_id} ({req_data["username"]}) created.'
        )

        assert res_data["data"]["user_id"] == str(user_id)

        # Check function calls
        mock_get_user.assert_called_once_with(
            username=req_data["username"],
            email=req_data["email"],
        )

        mock_save_user.assert_called_once()

    app.dependency_overrides.clear()


def test_create_user_unauthenticated(test_client: TestClient):
    """Test the "create_user" endpoint for an unauthenticated user.

    Args:
        test_client (TestClient): FastAPI test client.
    """
    # Request data
    req_data = {
        "username": "newuser",
        "password": "newusernewuser",
        "name": "New User",
        "email": "newuser@example.com",
        "staff": False,
        "admin": False,
        "enabled": True,
    }

    # Make HTTP request
    response = test_client.post("/users", json=req_data)

    # Check response
    assert response.status_code == status.HTTP_401_UNAUTHORIZED

    res_data = response.json()
    assert len(res_data) == 3

    assert res_data["message"] == "Authentication error."
    assert res_data["count"] == 1

    data = res_data["data"]
    assert len(data) == 1

    assert data[0]["id"] == "authentication"
    assert data[0]["message"] == "Not authenticated"


def test_create_user_unauthorized(app: FastAPI, test_client: TestClient):
    """Test the "create_user" endpoint for an unauthorized (disabled or not
    administrator) user.

    Args:
        app (FastAPI): FastAPI application.
        test_client (TestClient): FastAPI test client.
    """
    # Simulate the injected dependency
    app.dependency_overrides[get_admin_user] = raise_not_authorized_exc

    # Request data
    req_data = {
        "username": "newuser",
        "password": "newusernewuser",
        "name": "New User",
        "email": "newuser@example.com",
        "staff": False,
        "admin": False,
        "enabled": True,
    }

    # Make HTTP request
    response = test_client.post("/users", json=req_data)

    # Check response
    assert response.status_code == status.HTTP_403_FORBIDDEN

    res_data = response.json()
    assert len(res_data) == 3

    assert res_data["message"] == "Authorization error."
    assert res_data["count"] == 1

    data = res_data["data"]
    assert len(data) == 1

    assert data[0]["id"] == "authorization"
    assert data[0]["message"] == "Not authorized"

    app.dependency_overrides.clear()


def test_create_user_exists_username(
    app: FastAPI,
    test_client: TestClient,
    test_admin_user: User,
):
    """Test the "create_user" endpoint when a user with the same username already
    exists.

    Args:
        app (FastAPI): FastAPI application.
        test_client (TestClient): FastAPI test client.
        test_admin_user (User): Mock enabled administrator user.
    """
    # Simulate the injected dependency
    app.dependency_overrides[get_admin_user] = lambda: test_admin_user

    now = datetime.now(timezone.utc)

    # Simulate an existing user
    user = User(
        id=uuid4(),
        username="user1",
        password="user1user1",
        name="User 1",
        email="user1@example.com",
        staff=False,
        admin=False,
        enabled=True,
        created_at=now,
        updated_at=now,
    )

    # Request data
    req_data = {
        "username": "user1",
        "password": "user2user2",
        "name": "User 2",
        "email": "user2@example.com",
    }

    with patch("team_copilot.routers.users.get_us", return_value=user) as mock_get_user:
        # Make HTTP request
        response = test_client.post("/users", json=req_data)

        # Check response
        assert response.status_code == status.HTTP_409_CONFLICT

        res_data = response.json()
        assert len(res_data) == 3

        assert res_data["message"] == "Error."
        assert res_data["count"] == 1

        data = res_data["data"]

        assert len(data) == 1
        assert data[0]["id"] == "error"

        assert data[0]["message"] == (
            "A user with the same username or e-mail address already exists."
        )

        # Check function calls
        mock_get_user.assert_called_once_with(
            username=req_data["username"],
            email=req_data["email"],
        )


def test_create_user_user_exists_email(
    app: FastAPI,
    test_client: TestClient,
    test_admin_user: User,
):
    """Test the "create_user" endpoint when a user with the same e-mail address already
    exists.

    Args:
        app (FastAPI): FastAPI application.
        test_client (TestClient): FastAPI test client.
        test_admin_user (User): Mock enabled administrator user.
    """
    # Simulate the injected dependency
    app.dependency_overrides[get_admin_user] = lambda: test_admin_user

    now = datetime.now(timezone.utc)

    # Simulate an existing user
    user = User(
        id=uuid4(),
        username="user1",
        password="user1user1",
        name="User 1",
        email="user1@example.com",
        staff=False,
        admin=False,
        enabled=True,
        created_at=now,
        updated_at=now,
    )

    # Request data
    req_data = {
        "username": "user2",
        "password": "user2user2",
        "name": "User 2",
        "email": "user1@example.com",
    }

    with patch("team_copilot.routers.users.get_us", return_value=user) as mock_get_user:
        # Make HTTP request
        response = test_client.post("/users", json=req_data)

        # Check response
        assert response.status_code == status.HTTP_409_CONFLICT

        res_data = response.json()
        assert len(res_data) == 3

        assert res_data["message"] == "Error."
        assert res_data["count"] == 1

        data = res_data["data"]

        assert len(data) == 1
        assert data[0]["id"] == "error"

        assert data[0]["message"] == (
            "A user with the same username or e-mail address already exists."
        )

        # Check function calls
        mock_get_user.assert_called_once_with(
            username=req_data["username"],
            email=req_data["email"],
        )
