services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - TEAM_COPILOT_DEBUG=false
      - TEAM_COPILOT_DB_CONNECTION=postgresql://team_copilot:team_copilot@db:5432/team_copilot
      - TEAM_COPILOT_ANTHROPIC_API_KEY=${TEAM_COPILOT_ANTHROPIC_API_KEY}
    volumes:
      - ..:/home/vscode/team-copilot
    stdin_open: true
    tty: true

  db:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=team_copilot
      - POSTGRES_PASSWORD=team_copilot
      - POSTGRES_DB=team_copilot
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../src/team_copilot/db/setup.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]

  db-ui:
    image: adminer:4.17.1
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
