services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile-app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env_app
    volumes:
      - ..:/home/vscode/team-copilot
    stdin_open: true
    tty: true

  db:
    build:
      dockerfile: Dockerfile-db
    ports:
      - "5432:5432"
    env_file:
      - .env_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]

  db-ui:
    image: adminer:4.17.1
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
