services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile-app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - llm
    environment:
      - TEAM_COPILOT_DEBUG=false
      - TEAM_COPILOT_APP_HOST=0.0.0.0
      - TEAM_COPILOT_APP_PORT=8000
      - TEAM_COPILOT_APP_SECRET_KEY=${TEAM_COPILOT_APP_SECRET_KEY}
      - TEAM_COPILOT_APP_DOCS_DIR=/team-copilot-docs
      - TEAM_COPILOT_APP_ADMIN_USER=admin
      - TEAM_COPILOT_APP_ADMIN_PASSWORD=admin
      - TEAM_COPILOT_DB_URL=postgresql://team_copilot:team_copilot@db:5432/team_copilot
      - TEAM_COPILOT_OLLAMA_URL=http://llm:11434
      - TEAM_COPILOT_EMB_MODEL=nomic-embed-text
      - TEAM_COPILOT_LLM_MODEL=llama3:8b
    volumes:
      - ..:/home/vscode/team-copilot
    stdin_open: true
    tty: true

  db:
    build:
      dockerfile: Dockerfile-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=team_copilot
      - POSTGRES_PASSWORD=team_copilot
      - POSTGRES_DB=team_copilot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_preload_libraries=pg_stat_statements"]

  db-ui:
    image: adminer:4.17.1
    ports:
      - "8080:8080"
    depends_on:
      - db

  llm:
    build:
      dockerfile: Dockerfile-llm
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - EMB_MODEL=nomic-embed-text
      - LLM_MODEL=llama3:8b
    volumes:
      - ollama_models:/root/.ollama

volumes:
  postgres_data:
  ollama_models:
